### ISSUE TITLE
Set-CUCNotificationHTMLDevice

### ISSUE THREAD

**Issue by fullboat1010** [tjames192/PSCUC#1]
Hello and thanks for creating this module! I am currently using it to script the onboarding process at my organization. I am running into an issue with the Set-CUCNotificationHTMLDevice cmdlet. I am also hoping I can develop a similar cmdlet for an SMTP device. Here is what I get within PowerShell after using the following: Set-CUCNotificationHTMLDevice -alias rmanthe -DisplayName "TEST" -Enabled $true

Cannot index into a null array.
At C:\Windows\System32\WindowsPowerShell\v1.0\Modules\PSCUC\Public\Set-CUCNotificationHTMLDevice.ps1:33 char:27
+         $URI = "https://$($session['server'])/vmrest/users?query=(ali ...
+                           ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
 
Cannot index into a null array.
At C:\Windows\System32\WindowsPowerShell\v1.0\Modules\PSCUC\Public\Set-CUCNotificationHTMLDevice.ps1:35 char:9
+         $user = Invoke-RestMethod -Headers $session['headers'] -Uri $ ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
 
Cannot index into a null array.
At C:\Windows\System32\WindowsPowerShell\v1.0\Modules\PSCUC\Public\Set-CUCNotificationHTMLDevice.ps1:38 char:27
+         $URI = "https://$($session['server'])/vmrest/users/$($user.us ...
+                           ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
 
Cannot index into a null array.
At C:\Windows\System32\WindowsPowerShell\v1.0\Modules\PSCUC\Public\Set-CUCNotificationHTMLDevice.ps1:41 char:9
+         $NotificationDevices = (Invoke-RestMethod -Headers $session[' ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
 
Cannot index into a null array.
At C:\Windows\System32\WindowsPowerShell\v1.0\Modules\PSCUC\Public\Set-CUCNotificationHTMLDevice.ps1:46 char:27
+         $URI = "https://$($session['server'])$($NotificationDevice.UR ...
+                           ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
 
Cannot index into a null array.
At C:\Windows\System32\WindowsPowerShell\v1.0\Modules\PSCUC\Public\Set-CUCNotificationHTMLDevice.ps1:62 char:9
+         $irmSplat = @{
+         ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
 
Write-Warning : Cannot bind argument to parameter 'Message' because it is null.
At C:\Windows\System32\WindowsPowerShell\v1.0\Modules\PSCUC\Public\Set-CUCNotificationHTMLDevice.ps1:74 char:27
+             write-warning $apiErr.InnerException
+                           ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Write-Warning], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.WriteWarningCommand

**Comment by tjames192** [comment]
Hi and welcome,
So first I would make sure that you are connected to cuc. I was writing this module during our transition from Exchange UM to Cisco Unity. My environment might not exactly match yours but we can work through it.

If you are indeed connected the next troubleshooting is this line:
"https://$($session['server'])/vmrest/users?query=(alias is $($alias))"

we need to ensure this url and "rmanthe" is accurate for your instance
"https://<server>/vmrest/users?query=(alias is rmanthe)"

If you browse to that url? does it return results for you?

**Comment by fullboat1010** [comment]
I am connected to CUC just fine and am able to successfully import users, which is great! 

I navigated to the URL above and got the appropriate results returned with the document tree. The alias is correct.

**Comment by tjames192** [comment]
hmm ok let me write this one out as a seperate function with additional verbose messages may need to double check the variables and urls.
I just ran this command in my environment and it did not result an error.

**Comment by tjames192** [comment]
The error message is it cannot index into null array starting with this line:
$URI = "https://$($session['server'])/vmrest/users?query=(ali ...

which to me says that $session['server'] is null or empty

Can you share the output of..:
Connect-CUC
Set-CUCNotificationHTMLDevice -alias rmanthe -DisplayName "TEST" -Enabled $true -verbose

$PSVersionTable
[System.Environment]::OSVersion | fl
(Get-CUCConnectionLocation).SystemVersion

**Comment by fullboat1010** [comment]
![image](https://user-images.githubusercontent.com/34396626/84264886-990aa380-aae7-11ea-94bb-e550e4214997.png)

**Comment by fullboat1010** [comment]
I just tried again and did not get the warning message. 
![image](https://user-images.githubusercontent.com/34396626/84278376-4ab2d000-aafa-11ea-9ca2-9758f7b215f9.png)

**Comment by tjames192** [comment]
can you also provide the output of this?
Set-CUCNotificationHTMLDevice -alias rmanthe -DisplayName "TEST" -Enabled $true -verbose

**Comment by fullboat1010** [comment]
So, It looks like I got further than I did yesterday. But, I am not seeing this HTML device in CUC.
![image](https://user-images.githubusercontent.com/34396626/84312656-e9efbb80-ab2a-11ea-812b-1c1175f300f2.png)

**Comment by tjames192** [comment]
I suspect previously it was not really connected even though my script said it was.
When you connected 2x in the previous screenshot without red errors it looks like this is a solid connection.

Now this set command expects that TEST is available for the user rmanthe.
But the verbose output tells me that it's not available and was not truly selected.

What I would do is browse to that HTML Devices url provided in the verbose output a look at the display names list in the output.

**Comment by tjames192** [comment]
For reference..
if you go to cuc admin
users > users > (rmanthe) > edit > notification devices
The display names will match the output from browsing to rest api url

my set command would expect the html device display name to be available to enable / disable

![image](https://user-images.githubusercontent.com/11339835/84316310-c410e980-ab1f-11ea-8ed9-bf82115d631c.png)

**Comment by fullboat1010** [comment]
I browsed to the URL in the verbose Output and saw the three default HTML devices, none with the display name "TEST." Here is a screenshot of CUC:
![image](https://user-images.githubusercontent.com/34396626/84319304-6ab3b500-ab35-11ea-8bc4-79f72ce244fe.png)

**Comment by tjames192** [comment]
yep that's correct so the set command you have to specify1 of the defaults that exists or create a new html device for the user.

Set-CUCNotificationHTMLDevice -alias rmanthe -DisplayName "HTML Missed Call" -Enabled $true

The set command doesn't create a new html device

**Comment by tjames192** [comment]
if we want to create a new html device let's say
New-CUCNotificationHTMLDevice we would need to create this function.
I did not implement this command yet as I didn't need it for my environment.

**Comment by fullboat1010** [comment]
Now I am understanding. So in theory I should be able to change an existing HTML device. Here is what I get when I try to do that:

![image](https://user-images.githubusercontent.com/34396626/84413164-d9484f80-abd5-11ea-9d35-94fb8601fd3c.png)

**Comment by tjames192** [comment]
yes that is correct, which is why i chose the verb "set" and not "new" or "add".
So now we have a new problem I haven't encountered or even tested. Let me try in my setup.

**Comment by tjames192** [comment]
I just ran the command in my setup and i did not encounter an error. So this tells me there must be a prerequisite  setting that is preventing you from moving forward
![image](https://user-images.githubusercontent.com/11339835/84415562-c9c20a00-abc7-11ea-84a8-d1a2aa3b22ad.png)

**Comment by tjames192** [comment]
Is the TO field empty for you in the HTML Notification Device for rmanthe?
I suspect it probably is... when I did our setup I imported a CSV that should have pre-filled it.

**Comment by tjames192** [comment]
If you add an check on generate SMTP proxy address from corporate address then it should work for to enable. The problem now is the users' email address needs to be entered. I could probably also add a parameter for "SmtpAddress"

**Comment by tjames192** [comment]
If that's not it, then it's the notifcation template. I've hardcoded a notification template id that's specific to my environment. I need to enumerate all default notification templates and grab the id. I'll work on that post an update

**Comment by fullboat1010** [comment]
Thanks a ton!

**Comment by tjames192** [comment]
No problem. I posted an update in a new branch pending to be merged into master (has been tested in my setup). Give it a go and let me know if any errors...:
[https://github.com/tjames192/PSCUC/tree/add-enumerateNotificationTemplateIds](url)

added optional parameter NotificationTemplateName
Set-CUCNotificationHTMLDevice -alias demo@demo.com -DisplayName "HTML Scheduled Summary" -Enabled $true -NotificationTemplateName "Default_Missed_Call_With_Summary"

added new command Get-CUCNotificationTemplate
This will list all notification template names

**Comment by fullboat1010** [comment]
It worked! Thanks so much for your help!
![image](https://user-images.githubusercontent.com/34396626/84435611-baf34b80-abf7-11ea-800d-4530b2b536e0.png)

**Comment by fullboat1010** [comment]
Now I am going to try to do the same thing for SMTP rather than HTML....looks like it may be a little different. Thanks again.

**Comment by tjames192** [comment]
No problem. Yes this function will only work with HTML Devices.
Inside the code I am hardcoding htmldevices url.. so it definitely won't work with SMTP or any other option.

I don't have any logic created to handle SMTP, Pager and Phone options

I'll go ahead merge the pull request which will mark this issue as resolved.

You can open a new issue for me to add SMTP, Pager and Phone options.
