### ISSUE TITLE
Set-CUCNotificationSMTPDevice

### ISSUE THREAD

**Issue by fullboat1010** [tjames192/PSCUC#3]
Can you create a cmdlet to enable and set the email address for an SMTP device in CUC?

**Comment by tjames192** [comment]
sure can, do you have any specific options you want to customize? or just looking for bare bones enable/disable?

**Comment by fullboat1010** [comment]
Worked like a charm!! Thanks a ton!

**Comment by tjames192** [comment]
No problem!
