### ISSUE TITLE
Remove-CUCUser

### ISSUE THREAD

**Issue by fullboat1010** [tjames192/PSCUC#5]
I found an issue with the Remove-CUCUser cmdlet. There is an extra / in the URI for the delete request. Here is what the verbose output was before I changed the code:

![image](https://user-images.githubusercontent.com/34396626/86150068-7ce49b80-bac2-11ea-94ed-e88341c37d10.png)

I removed the / in the second URI so it looks like this:

![image](https://user-images.githubusercontent.com/34396626/86150174-a6052c00-bac2-11ea-8ee5-294fbfdd4b68.png)

Here is the verbose output after the change:

![image](https://user-images.githubusercontent.com/34396626/86150229-bfa67380-bac2-11ea-9210-73789b6aca25.png)

**Comment by tjames192** [comment]
Cool thanks I will patch master code.
